// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/storefront-makeover/Current.tsx": () => import("../components/mockups/storefront-makeover/Current.tsx"),
  "./components/mockups/storefront-makeover/PremiumShopDesk.tsx": () => import("../components/mockups/storefront-makeover/PremiumShopDesk.tsx")
};
