// Generated schemas — export everything EXCEPT UpdateProductBody which is
// overridden by the hand-written extension in productActions.ts below.
export {
  HealthCheckResponse,
  GetSettingsResponse,
  UpdateSettingsBody,
  UpdateSettingsResponse,
  ListReceiptTemplatesResponseItem,
  ListReceiptTemplatesResponse,
  CreateReceiptTemplateBody,
  CreateReceiptTemplateResponse,
  GetDefaultReceiptTemplateResponse,
  GetReceiptTemplateParams,
  GetReceiptTemplateResponse,
  UpdateReceiptTemplateParams,
  UpdateReceiptTemplateBody,
  UpdateReceiptTemplateResponse,
  DeleteReceiptTemplateParams,
  DeleteReceiptTemplateResponse,
  SetDefaultReceiptTemplateParams,
  SetDefaultReceiptTemplateResponse,
  GetMyRoleResponse,
  ListUsersResponseItem,
  ListUsersResponse,
  UpdateUserRoleParams,
  UpdateUserRoleBody,
  UpdateUserRoleResponse,
  DeleteUserParams,
  DeleteUserResponse,
  ListCategoriesResponseItem,
  ListCategoriesResponse,
  CreateCategoryBody,
  CreateCategoryResponse,
  UpdateCategoryParams,
  UpdateCategoryBody,
  UpdateCategoryResponse,
  DeleteCategoryParams,
  DeleteCategoryResponse,
  ListProductsQueryParams,
  ListProductsResponseItem,
  ListProductsResponse,
  createProductBodyPriceMin,
  createProductBodyCostPriceMin,
  createProductBodyStockMin,
  createProductBodyReorderLevelMin,
  CreateProductBody,
  CreateProductResponse,
  GetProductParams,
  GetProductResponse,
  UpdateProductParams,
  updateProductBodyPriceMin,
  updateProductBodyCostPriceMin,
  updateProductBodyStockMin,
  updateProductBodyReorderLevelMin,
  // UpdateProductBody intentionally omitted — re-exported from productActions.ts
  UpdateProductResponse,
  DeleteProductParams,
  DeleteProductResponse,
  AdjustStockParams,
  AdjustStockBody,
  AdjustStockResponse,
  ListSalesQueryParams,
  ListSalesResponseItem,
  ListSalesResponse,
  createSaleBodyPaymentMethodDefault,
  createSaleBodyCartDiscountMin,
  createSaleBodyItemsItemDiscountMin,
  CreateSaleBody,
  CreateSaleResponse,
  GetSaleParams,
  GetSaleResponse,
  RequestUploadUrlBody,
  RequestUploadUrlResponse,
  GetStorageObjectParams,
  GetStorageObjectResponse,
  GetDashboardSummaryResponse,
  GetSalesByDayResponseItem,
  GetSalesByDayResponse,
  GetTopProductsResponseItem,
  GetTopProductsResponse,
  GetLowStockProductsResponseItem,
  GetLowStockProductsResponse,
} from "./generated/api";
export * from "./stockTransfers";
export * from "./productActions";
// Selective type re-exports — omit names that conflict with Zod schema exports above
export type {
  AppUser,
  AppUserRoleUpdate,
  Category,
  CategoryInput,
  DailySales,
  DashboardSummary,
  HealthStatus,
  ListProductsParams,
  ListSalesParams,
  MyRoleResponse,
  Product,
  ProductInput,
  ProductUpdate,
  Sale,
  SaleInput,
  SaleItem,
  SaleItemInput,
  StockAdjustment,
  TopProduct,
} from "./generated/types";
